### PR TITLE
search, credits, results page added

### PR DESCRIPTION
**Pull request by mndcheng**

### CODE REVIEW

**Comment by mndcheng** [comment]
@skariyadan feel free to delete branch when done merging

**Comment by mndcheng** [comment]
known issue: add song inputs don't take files--program crashes?

**Review by maxwey — APPROVED** [review]

**Comment by maxwey** [comment]
@mndcheng  Go ahead and squash & merge, but could you add the US/issues that this merge addresses?

**Comment by mndcheng** [comment]
Initial commit to allow for adding song files to the database.
See issue #41 .

**Comment by mndcheng** [comment]
Initial commit to build UI that lets users have an advanced search feature.
See issue #37 .

**Pull request merged**
